server:
    port: 8088
spring:
    jackson:
        time-zone: UTC
    data:
        mongodb:
            host: mongo
            port: 27017
            database: spring_boot_mongo_app
    application:
        name: crime-reports-service
